{% set name = "modflowapi" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/modflowapi-{{ version }}.tar.gz
  sha256: b214b22d1881940b6c42586681baa6595c63d93664a5508a9ab9afd75f784d23

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - numpy
    - xmipy
    - pandas
  run:
    - python >=3.8
    - numpy
    - xmipy
    - pandas

test:
  imports:
    - modflowapi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MODFLOW-USGS/modflowapi.git
  summary: modflowapi is an extension to the xmipy Python package.
  license: CC0-1.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jdhughes-usgs
    - jlarsen-usgs
    - w-bonelli
