{% set name = "modflowapi" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/modflowapi-{{ version }}.tar.gz
  sha256: ffe340c2a2634c6936d42d37b6292a4a4c8f3d5d466185a58ea49fc9d4780576

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - numpy
    - xmipy
    - pandas
  run:
    - python >={{ python_min }}
    - numpy
    - xmipy
    - pandas

test:
  imports:
    - modflowapi
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/MODFLOW-USGS/modflowapi.git
  summary: modflowapi is an extension to the xmipy Python package.
  license: CC0-1.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jdhughes-usgs
    - jlarsen-usgs
    - wpbonelli
