{% set name = "modflowapi" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/modflowapi-{{ version }}.tar.gz
  sha256: 2267c5caf822c236f45cd493c0121200d16ecd046bdb434260d6847c3de2a5f0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - xmipy

test:
  imports:
    - modflowapi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MODFLOW-USGS/modflowapi.git
  summary: modflowapi is an extension to the xmipy Python package.
  license: CC0-1.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jdhughes-usgs
